on: push
name: deploy

jobs:
  # 01 - crear y publicar la imagen docker
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
      - uses: mr-smithers-excellent/docker-build-push@v5
        with: 
          image: chux2000/github_action_test/clayvnc
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # uses: docker/build-push-action@v2
      # with:
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
            # repository: ${{ github.repository }}
            # tag_with_ref: true
            # tag_with_sha: true
            # tags: ${{ github.sha }}
  # 02 - crear VM en upcloud con terraform
